baseURL = 'https://blogs.silverliningresearch.org/'
languageCode = 'en-us'
title = ' How to run Earth Science Models in the Cloud! stay tuned! This site is in actively work.'
theme = 'ananke'

[params]
  subtitle = 'Brought to you by SilverLining NGO'
  text_color = "" 
  email = 'lhedges@silverlining.ngo'
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-blue"
  recent_posts_number = 10

