baseURL = 'https://blogs.silverliningresearch.org/'
languageCode = 'en-us'
title = ' Posts to run Earth Science Models in the Cloud! Brought to you by SilverLining NGO, Stay tuned! This site is in actively work.'
theme = 'ananke'

[params]
  text_color = "" 
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-blue"
  recent_posts_number = 10

